# -*- coding: utf-8 -*-
"""
Created on Tue Jul  6 16:04:15 2021

@author: Sushant Gour
"""


"""
This code is used to extract audio from a video. We need this code because we need the 
audio of the movie for speech transcription.


Tool used: ffmpeg


Inputs: The inputs required by this file are:
(1)	video_path: It is the path where the movie (mp4) is stored
(2)	video: The name of the movie (mp4)
(3)	audio: The name of the audio file that will be generated by this code (mp3)


Output: An audio file (mp3) will be created in the video_path directory having the name 
equal to the string represented by the audio variable.
"""
import os


# Inputs:
video_path = "C:/Users/DELL/Desktop/Sushant Internship Project"
os.chdir(video_path)
video= "JokerReal.mp4"
audio= "JokerReal.mp3"


call= "ffmpeg -i" + " " + video + " " + "-vn -sn -c:a mp3 -ab 192k" + " " + audio

# This method produces an mp3 file of exactly the same duration as of the input mp4 file.
#call= f'ffmpeg -i JokerReal.mp4 -vn -sn -c:a mp3 -ab 192k JokerReal.mp3'

os.system(call)
