# -*- coding: utf-8 -*-
"""
Created on Wed Jul 21 01:23:44 2021

@author: DELL
"""

"""
This code is used to convert an mp3 file to a wav file. We use this code because the input audio used in the horror scenes extraction pipeline has to be in wav format.


Tool used: ffmpeg


Inputs: The inputs required by this file are:
(1)	audio_path: It is the path where the audio of the movie (mp3) is stored
(2)	audio_mp3: The name of the audio file of the movie (mp3)
(3)	audio_wav: The name of the audio file that will be generated by this code (wav)


Output: An audio file (wav) will be created in the audio_path directory having the name equal 
to the string represented by the audio_wav variable.
"""
import os


# Path to the mp3 audio file of the movie
audio_path = "C:/Users/DELL/Desktop/Sushant Internship Project"
os.chdir(audio_path)

# name of the mp3 audio file
audio_mp3= "JokerReal.mp3"
# the name which we want to give to the wav file generated by this code
audio_wav= "JokerReal.wav"


call= "ffmpeg -i" + " " + audio_mp3  + " " + audio_wav
os.system(call)